version: '3.8'

services:
  app:
    build: .
    restart: unless-stopped
    depends_on:
      - postgres
    environment:
      - BOT_TOKEN=${BOT_TOKEN}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - DATABASE_URL=postgresql://espressoai:${POSTGRES_PASSWORD}@postgres:5432/espressoai
      - NOTIFICATION_CHECK_INTERVAL=${NOTIFICATION_CHECK_INTERVAL:-60000}
      - DEFAULT_NEWS_CHECK_INTERVAL=${DEFAULT_NEWS_CHECK_INTERVAL:-30}
      - MAX_SUBSCRIPTIONS_PER_USER=${MAX_SUBSCRIPTIONS_PER_USER:-10}
      - LOG_LEVEL=${LOG_LEVEL:-info}

  postgres:
    image: postgres:latest
    restart: unless-stopped
    environment:
      - POSTGRES_USER=espressoai
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=espressoai
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  postgres-data: